service: fcc
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DATABASE_URL: ${env.DATABASE_URL, "fallback value"}
    DEBUG: ${env.DATABASE_URL,0}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
