service: aws-api-http
frameworkVersion: "3"

provider:
  name: aws
  architecture: x86_64
  runtime: nodejs20.x
  region: ap-south-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: GET
